spring:
   profiles:
      active: prod


---

com:
  bit:
    wonders:
      app:
        message: "Hello World from AZURE"
        version: 1.0

server:
   port: 9090
   ssl:
      enabled: false
      key-store-type: PKCS12
      key-store: classpath:keystore/springkeystore.p12
      key-store-password: changeit
      key-alias: springkeystore
spring:
    config:
       activate:
           on-profile: "prod"
    mvc:
      pathmatch:
            matching-strategy: ant_path_matcher
    security:
      oauth2:
        client:
          registration:
            github:
              clientId: 4ff02e76486276fe90bf
              clientSecret: c1f9500a03fa0fe2f4a1f102f56b2a6669f4e7de

---

spring:
  config:
    activate:
      on-profile: "dev"

com:
  bit:
    wonders:
      app:
        message: "This is dev"


